export default {
  products: [
    {
      _id: "1",
      name: "Slim shirt",
      category: "Shirts",
      images: "/images/d1.jpg",
      price: 60,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
    },
    {
      _id: "2",
      name: "Fit shirt",
      category: "Shirts",
      images: "/images/d1.jpg",
      price: 40,
      brand: "Nike",
      rating: 4.2,
      numReviews: 10,
    },
    {
      _id: "3",
      name: " best Pants",
      category: "pants",
      images: "/images/d1.jpg",
      price: 50,
      brand: "Nike",
      rating: 4.0,
      numReviews: 8,
    },
    {
      _id: "4",
      name: "best shirt",
      category: "Shirts",
      images: "/images/d1.jpg",
      price: 70,
      brand: "Nike",
      rating: 4.3,
      numReviews: 10,
    },
  ],
};
