export const USER_SIGNIN_REQUEST = "USER_SIGNIN_REQUEST";
export const USER_SIGNIN_SUCCESS = "USER_SIGNIN_SUCCESS";
export const USER_SIGNIN_FAIL = "USER_SIGNIN_FAIL";

export const USER_REGISTER_REQUEST = "USER_REGISTER__REQUEST";
export const USER_REGISTER__SUCCESS = "USER_REGISTER__SUCCESS";
export const USER_REGISTER__FAIL = "USER_REGISTER__FAIL";
